### ISSUE TITLE
Problem with creation Jira ticket (custo field)

### ISSUE THREAD

**Issue by jrkf** [reportportal/plugin-bts-jira#38]
When I try POST ISSUE from RP I have response: 409 Conflict besause:
Impossible interact with integration. [ErrorCollectionstatus=400, errors=customfield_XXXX=data was not an array
We have special field in Jira which is array not a String
There is any posibility to send data as a array? 

RP ver 5.7 
Jira plugin ver 5.7

**Comment by DzmitryHumianiuk** [comment]
@jrkf only after modification of Jira plugin.

Since it's a plugin, you can easily modify it and re-upload your custom version into the running RP.
Don't hesitate to take a look into it.
Since we will not put hands deeply into something which should be connected with customized. 
Unless it's a paid support.

thank you.
